#!/bin/bash

### BEGIN INIT INFO
# Provides:          bontasite
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Runs the bontasite application.
# Description:       Starts and stops the bontasite application
### END INIT INFO

NAME=bontasite
DIR=/node/bontasite

BINARYNAME=node
NODE=/usr/sbin/node

case "$1" in
    start)
        echo -n "Starting the $NAME server... "
	    if [ -e "$BINARYNAME" ]; then
            daemon --name=bontasite --user=node -X "node $DIR/app.js"
        else
            echo "Could not find binary, aborting!"
            exit 5
        fi
        if [ `pgrep $BINARYNAME` ]; then
            echo "Done!"
        else
            echo "Failed!"
        fi
    ;;
    stop)
        echo -n "Stopping the $NAME server... "
        killall $BINARYNAME > /dev/null 2>/dev/null
        echo "Done!"
    ;;
    status)
        if [ `pgrep $BINARYNAME` ]; then
            echo "$NAME server is running"
        else
            echo "No $NAME server running"
        fi
    ;;
    *)
        echo "Usage: ${0} {start|stop|status}"
        exit 2
esac
exit 0